import 'dotenv/config';
import { GoogleGenAI } from '@google/genai';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

/**
 * Nano Banana 2 (gemini-3.1-flash-image-preview)
 * High-efficiency image generation optimised for speed + volume.
 * Returns base64-encoded PNG via response_modalities: ['IMAGE'].
 */
export const IMAGE_MODEL = 'gemini-3.1-flash-image-preview' as const;

interface InfographicResult {
  imageBase64: string;
  mimeType: string;
  caption?: string;
}

/**
 * Generate a FIRE roadmap infographic using Nano Banana 2.
 * Takes structured FIRE data and produces a visual summary card.
 */
export async function generateFireInfographic(params: {
  age: number;
  retireAge: number;
  income: number;
  successProbability: number;
  p50Corpus: number;
  requiredSip: number;
  insuranceGap: number;
  macroSourceMode: string;
}): Promise<InfographicResult> {
  const prompt = `Create a clean, modern financial infographic card for an Indian retirement (FIRE) plan. The design should use a dark navy (#040A18) background with gold (#D4AF37) accents and white text.

Layout (single card, aspect ratio 3:2):
- Top: Large bold title "FIRE Roadmap" with a small flame emoji
- Below title: "Age ${params.age} → Retire by ${params.retireAge}" in gold text

Key metrics displayed in a clean grid:
- Success Probability: ${params.successProbability.toFixed(0)}% (use green if >60%, amber if 30-60%, red if <30%)
- P50 Retirement Corpus: ₹${(params.p50Corpus / 10000000).toFixed(1)} Cr
- Required Monthly SIP: ₹${(params.requiredSip / 1000).toFixed(0)}K
- Insurance Gap: ₹${(params.insuranceGap / 100000).toFixed(0)}L ${params.insuranceGap > 0 ? '⚠️' : '✅'}
- Annual Income: ₹${(params.income / 100000).toFixed(0)}L

Bottom: Small text "Generated by ChanakAI • Monte Carlo simulation • Not financial advice" and "Macro data: ${params.macroSourceMode}"

Style: Professional financial dashboard aesthetic. Clean sans-serif typography. Minimal, no clutter. Dark theme with subtle gradients.`;

  const response = await ai.models.generateContent({
    model: IMAGE_MODEL,
    contents: [prompt],
    config: {
      responseModalities: ['IMAGE'],
      imageConfig: {
        aspectRatio: '3:2',
        imageSize: '1K',
      },
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts ?? []) {
    if (part.inlineData) {
      return {
        imageBase64: part.inlineData.data!,
        mimeType: part.inlineData.mimeType || 'image/png',
        caption: `FIRE Roadmap: ${params.successProbability.toFixed(0)}% success probability | ₹${(params.requiredSip / 1000).toFixed(0)}K/mo SIP needed`,
      };
    }
  }

  throw new Error('Nano Banana 2 did not return an image.');
}

/**
 * Generate a portfolio summary infographic using Nano Banana 2.
 */
export async function generatePortfolioInfographic(params: {
  xirr: number;
  benchmarkReturn: number;
  expenseDrag: number;
  overlappingStocks: number;
  totalValue: number;
  fundCount: number;
}): Promise<InfographicResult> {
  const outperforming = params.xirr > params.benchmarkReturn;

  const prompt = `Create a clean, modern financial infographic card for a mutual fund portfolio analysis. Dark navy (#040A18) background with gold (#D4AF37) accents and white text.

Layout (single card, aspect ratio 3:2):
- Top: Large bold title "Portfolio X-Ray" with a chart/pie icon
- Subtitle: "${params.fundCount} funds analysed" in slate text

Key metrics in a clean 2x2 grid:
- True XIRR: ${params.xirr.toFixed(1)}% (${outperforming ? 'green — outperforming' : 'red — underperforming'} benchmark)
- Benchmark (Nifty 500): ${params.benchmarkReturn.toFixed(1)}%
- Annual Expense Drag: ₹${(params.expenseDrag / 1000).toFixed(0)}K/yr
- Overlapping Stocks: ${params.overlappingStocks} stocks across funds

${outperforming ? 'A subtle upward arrow or green indicator showing outperformance.' : 'A subtle amber indicator suggesting rebalancing opportunity.'}

Portfolio Value: ₹${(params.totalValue / 100000).toFixed(0)}L displayed prominently.

Bottom: Small text "Generated by ChanakAI • Multi-agent analysis • Not investment advice"

Style: Professional financial dashboard aesthetic. Clean sans-serif typography. Dark theme, navy + gold palette. Minimal and modern.`;

  const response = await ai.models.generateContent({
    model: IMAGE_MODEL,
    contents: [prompt],
    config: {
      responseModalities: ['IMAGE'],
      imageConfig: {
        aspectRatio: '3:2',
        imageSize: '1K',
      },
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts ?? []) {
    if (part.inlineData) {
      return {
        imageBase64: part.inlineData.data!,
        mimeType: part.inlineData.mimeType || 'image/png',
        caption: `Portfolio X-Ray: ${params.xirr.toFixed(1)}% XIRR | ${params.overlappingStocks} overlapping stocks`,
      };
    }
  }

  throw new Error('Nano Banana 2 did not return an image.');
}

/**
 * Generate a tax comparison infographic using Nano Banana 2.
 */
export async function generateTaxInfographic(params: {
  oldRegimeTax: number;
  newRegimeTax: number;
  savings: number;
  winner: 'old' | 'new';
  grossSalary: number;
  missedDeductions: number;
}): Promise<InfographicResult> {
  const prompt = `Create a clean, modern financial infographic card comparing two tax regimes for an Indian taxpayer. Dark navy (#040A18) background with gold (#D4AF37) accents and white text.

Layout (single card, aspect ratio 3:2):
- Top: Large bold title "Tax Comparison — FY 2025-26" with a calculator icon
- Subtitle: "Gross Salary: ₹${(params.grossSalary / 100000).toFixed(0)}L" in gold text

Main comparison — two columns side by side:
- Left column: "Old Regime" with tax amount ₹${(params.oldRegimeTax / 1000).toFixed(0)}K ${params.winner === 'old' ? '✅ WINNER' : ''}
- Right column: "New Regime" with tax amount ₹${(params.newRegimeTax / 1000).toFixed(0)}K ${params.winner === 'new' ? '✅ WINNER' : ''}

Highlight: "You save ₹${(params.savings / 1000).toFixed(0)}K with ${params.winner === 'new' ? 'New' : 'Old'} Regime" in green text

${params.missedDeductions > 0 ? `Alert: "₹${(params.missedDeductions / 1000).toFixed(0)}K in missed deductions detected" in amber` : ''}

Bottom: "Generated by ChanakAI • Deterministic engine • Not tax advice"

Style: Professional financial dashboard. Clean typography. Dark theme, navy + gold. Two-column comparison layout.`;

  const response = await ai.models.generateContent({
    model: IMAGE_MODEL,
    contents: [prompt],
    config: {
      responseModalities: ['IMAGE'],
      imageConfig: {
        aspectRatio: '3:2',
        imageSize: '1K',
      },
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts ?? []) {
    if (part.inlineData) {
      return {
        imageBase64: part.inlineData.data!,
        mimeType: part.inlineData.mimeType || 'image/png',
        caption: `Tax ${params.winner === 'new' ? 'New' : 'Old'} Regime saves ₹${(params.savings / 1000).toFixed(0)}K`,
      };
    }
  }

  throw new Error('Nano Banana 2 did not return an image.');
}
