import { useState, useRef, useEffect, type Dispatch, type SetStateAction } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { PieChart, Flame, Calculator, ShieldAlert, FileText, ChevronDown, ChevronUp, User, Clock, CheckCircle2, AlertTriangle } from 'lucide-react';
import { cn } from '../lib/utils';
import { PortfolioXRay } from './PortfolioXRay';
import { FIRERoadmap } from './FIRERoadmap';
import { TaxWizard } from './TaxWizard';
import { ErrorBoundary } from './ErrorBoundary';
import { useAnalysis } from '../contexts/AnalysisContext';
import { ChatMentor } from './ChatMentor';
import type { UserProfile, UploadedDocument } from '../App';
import type { AgentEvent } from '../hooks/useSSE';

type Tab = 'portfolio' | 'fire' | 'tax';

const SEBI_DISCLAIMER = `This analysis is generated by ChanakAI, an AI-powered educational tool. The calculations, projections, and recommendations presented here are for informational and educational purposes only. They do not constitute investment advice, financial planning advice, or any other form of regulated financial service. Past performance of mutual funds does not guarantee future returns. Tax calculations are based on declared inputs and publicly available FY 2025-26 regulations — please verify with a qualified tax professional. Please consult a SEBI-registered investment advisor (RIA) before making any financial decisions. ChanakAI is not a SEBI-registered entity.`;

export function Dashboard({ profile, setProfile, uploadedDocs = [], onStartOver }: { profile: UserProfile; setProfile: Dispatch<SetStateAction<UserProfile>>; uploadedDocs?: UploadedDocument[]; onStartOver?: () => void }) {
  const [activeTab, setActiveTab] = useState<Tab>('portfolio');
  const [auditOpen, setAuditOpen] = useState(false);
  const { firePipeline, portfolioPipeline, taxPipeline, getCrossPipelineData } = useAnalysis();

  // Derive parsed data from uploaded documents
  const parsedCas = uploadedDocs.find(d => d.parsedData?.type === 'cas')?.parsedData;
  const parsedForm16 = uploadedDocs.find(d => d.parsedData?.type === 'form16')?.parsedData;
  const parsedPayslip = uploadedDocs.find(d => d.parsedData?.type === 'payslip')?.parsedData;
  const [showExtractedData, setShowExtractedData] = useState(false);

  // Auto-populate profile from Form16 parsed data
  const hasAutoPopulatedRef = useRef(false);
  useEffect(() => {
    if (hasAutoPopulatedRef.current) return;
    if (parsedForm16 && parsedForm16.confidence > 0.5) {
      hasAutoPopulatedRef.current = true;
      const data = parsedForm16.data as {
        grossSalary?: number;
        deductions?: { section: string; amount: number }[];
        taxDeducted?: number;
      };
      setProfile(p => ({
        ...p,
        income: data.grossSalary || p.income,
        section80C: data.deductions?.find(d => d.section.includes('80C') && !d.section.includes('80CCD'))?.amount || p.section80C,
        section80D: data.deductions?.find(d => d.section.includes('80D'))?.amount || p.section80D,
        section80CCD1B: data.deductions?.find(d => d.section.includes('80CCD'))?.amount || p.section80CCD1B,
      }));
    }
  }, [parsedForm16, setProfile]);

  // Aggregate real events from all three pipelines for audit trail
  const allEvents: (AgentEvent & { pipeline: string })[] = [
    ...portfolioPipeline.events.map(e => ({ ...e, pipeline: 'Portfolio' })),
    ...firePipeline.events.map(e => ({ ...e, pipeline: 'FIRE' })),
    ...taxPipeline.events.map(e => ({ ...e, pipeline: 'Tax' })),
  ].sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

  const auditEntries = (() => {
    // Group by agent
    const groups = new Map<string, { start?: AgentEvent & { pipeline: string }; complete?: AgentEvent & { pipeline: string } }>();
    for (const e of allEvents) {
      if (e.agent === 'Pipeline') continue;
      const key = `${e.pipeline}::${e.agent}`;
      if (!groups.has(key)) groups.set(key, {});
      const g = groups.get(key)!;
      if (e.type === 'agent_start') g.start = e;
      if (e.type === 'agent_complete') g.complete = e;
    }

    return Array.from(groups.entries()).map(([key, g]) => {
      const [pipeline, agent] = key.split('::');
      const isDeterministic = agent.includes('Engine') || agent.includes('Regime') || agent.includes('Profiler') || agent.includes('Gap');
      const isFlash = agent.includes('Checker') || agent.includes('Injector') || agent.includes('Collector') || agent.includes('Macro');
      const model = isDeterministic ? 'Deterministic Engine' : isFlash ? 'Gemini Flash' : 'Gemini Pro';
      const latency = g.complete?.latencyMs;
      return { pipeline, agent, model, latency: latency !== undefined ? `${latency}ms` : '—' };
    });
  })();

  // Count documents per module
  const portfolioDocs = uploadedDocs.filter(d => d.docType === 'cams' || d.docType === 'demat').length;
  const fireDocs = uploadedDocs.filter(d => d.docType === 'bankstmt' || d.docType === 'insurance').length;
  const taxDocs = uploadedDocs.filter(d => d.docType === 'form16').length;

  return (
    <div className="h-screen bg-[#0a0a0a] flex flex-col md:flex-row overflow-hidden">
      {/* 1. Left Sidebar */}
      <aside className="w-full md:w-64 bg-[#141414] border-r border-[#2a2a2a] flex flex-col shrink-0 overflow-y-auto shadow-2xl z-10">
        <div className="p-6">
          <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
            <img src="/logo1.png" alt="ChanakAI Logo" className="w-10 h-10 object-cover rounded-full shadow-[0_0_15px_rgba(0,229,255,0.4)]" />
            <span className="bg-gradient-to-r from-teal-400 to-blue-500 bg-clip-text text-transparent">ChanakAI</span>
          </h1>
        </div>

        <nav className="flex-1 px-4 space-y-2">
          {/* User Profile Summary */}
          {profile.city && (
            <div className="mb-4 p-3 bg-[#0a0a0a]/50 rounded-xl border border-[#2a2a2a] backdrop-blur-sm">
              <div className="flex items-center gap-2 mb-2">
                <User className="w-4 h-4 text-teal-400" />
                <span className="text-xs font-semibold uppercase tracking-wider text-teal-400">Profile</span>
              </div>
              <p className="text-sm text-white font-medium">{profile.city}, Age {profile.age}</p>
              <p className="text-xs text-slate-400">Income: ₹{(profile.income / 100000).toFixed(0)}L/yr</p>
              {profile.retireAge > 0 && (
                <p className="text-xs text-slate-400">Retire by: {profile.retireAge} • SIP: ₹{profile.monthlySipCurrent ? (profile.monthlySipCurrent / 1000).toFixed(0) + 'K' : '—'}/mo</p>
              )}
            </div>
          )}

          <button
            onClick={() => setActiveTab('portfolio')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'portfolio' ? "bg-[#1f1f1f] text-teal-400 shadow-md border border-[#333]" : "text-slate-400 hover:text-slate-200 hover:bg-[#1a1a1a]"
            )}
          >
            <PieChart className="w-5 h-5" />
            <span className="font-medium flex-1 text-left">Portfolio X-Ray</span>
            {portfolioDocs > 0 && <span className="text-[10px] bg-teal-500/20 text-teal-400 px-1.5 py-0.5 rounded-full font-mono">{portfolioDocs} doc{portfolioDocs > 1 ? 's' : ''}</span>}
          </button>
          
          <button
            onClick={() => setActiveTab('fire')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'fire' ? "bg-[#1f1f1f] text-teal-400 shadow-md border border-[#333]" : "text-slate-400 hover:text-slate-200 hover:bg-[#1a1a1a]"
            )}
          >
            <Flame className="w-5 h-5" />
            <span className="font-medium flex-1 text-left">FIRE Roadmap</span>
            {fireDocs > 0 && <span className="text-[10px] bg-teal-500/20 text-teal-400 px-1.5 py-0.5 rounded-full font-mono">{fireDocs} doc{fireDocs > 1 ? 's' : ''}</span>}
          </button>

          <button
            onClick={() => setActiveTab('tax')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'tax' ? "bg-[#1f1f1f] text-teal-400 shadow-md border border-[#333]" : "text-slate-400 hover:text-slate-200 hover:bg-[#1a1a1a]"
            )}
          >
            <Calculator className="w-5 h-5" />
            <span className="font-medium flex-1 text-left">Tax Wizard</span>
            {taxDocs > 0 && <span className="text-[10px] bg-teal-500/20 text-teal-400 px-1.5 py-0.5 rounded-full font-mono">{taxDocs} doc{taxDocs > 1 ? 's' : ''}</span>}
          </button>

          {/* Uploaded Documents Summary in Sidebar */}
          {uploadedDocs.length > 0 && (
            <div className="mt-4 p-3 bg-[#0a0a0a]/50 rounded-xl border border-[#2a2a2a] backdrop-blur-sm">
              <div className="flex items-center gap-2 mb-2">
                <FileText className="w-4 h-4 text-teal-400" />
                <span className="text-xs font-semibold uppercase tracking-wider text-teal-400">Documents</span>
              </div>
              {uploadedDocs.map((doc, i) => (
                <div key={i} className="flex items-center gap-1.5 mb-1 last:mb-0">
                  {doc.parseStatus === 'done' && doc.parsedData ? (
                    <CheckCircle2 className="w-3 h-3 text-teal-500 shrink-0" />
                  ) : doc.parseStatus === 'error' ? (
                    <AlertTriangle className="w-3 h-3 text-red-500 shrink-0" />
                  ) : (
                    <span className="w-3 h-3 rounded-full bg-[#2a2a2a] shrink-0 inline-block" />
                  )}
                  <p className="text-[10px] text-slate-400 truncate flex-1" title={doc.file.name}>
                    {doc.file.name.length > 20 ? doc.file.name.slice(0, 20) + '…' : doc.file.name}
                  </p>
                  {doc.parseStatus === 'done' && doc.parsedData && (
                    <span className="text-[9px] text-teal-500 font-mono shrink-0">{Math.round(doc.parsedData.confidence * 100)}%</span>
                  )}
                  {!doc.parseStatus && <span className="text-[9px] text-slate-600 shrink-0">pending</span>}
                </div>
              ))}
            </div>
          )}
        </nav>

        <div className="p-4 mt-auto space-y-3">
          {onStartOver && (
            <button
              onClick={onStartOver}
              className="w-full py-2.5 text-sm font-medium text-slate-400 hover:text-white border border-[#2a2a2a] hover:border-teal-500/50 rounded-xl transition-colors"
            >
              ← Start Over
            </button>
          )}
          <div className="p-4 bg-[#1a1a1a] rounded-xl border border-[#333] space-y-3">
            <div className="flex items-center gap-2 text-slate-300">
              <ShieldAlert className="w-4 h-4 text-teal-400" />
              <span className="text-xs font-medium uppercase tracking-wider">Compliance</span>
            </div>
            <p className="text-[10px] text-slate-500 leading-relaxed">
              SEBI-compliant educational tool. Not investment advice. See full disclaimer below each analysis.
            </p>
          </div>
        </div>
      </aside>

      {/* 2. Center Content Area */}
      <main className="flex-1 overflow-y-auto p-4 md:p-8 bg-[#0a0a0a] relative">
        <div className="max-w-5xl mx-auto space-y-8">
          
          {/* Document Data Available banner */}
          {(parsedCas || parsedForm16 || parsedPayslip) && (
            <div className="mb-6 p-4 bg-teal-500/10 border border-teal-500/20 rounded-2xl space-y-2 backdrop-blur-md">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-teal-400" />
                <span className="text-sm font-semibold text-teal-400">Extracted Document Data Available</span>
                <button
                  onClick={() => setShowExtractedData(!showExtractedData)}
                  className="ml-auto text-xs text-teal-200 hover:text-white transition-colors bg-teal-500/20 px-3 py-1 rounded-full"
                >
                  {showExtractedData ? 'Hide details' : 'View extracted data'}
                </button>
              </div>
              <div className="space-y-1">
                {parsedCas && (
                  <p className="text-xs text-slate-300">
                    <CheckCircle2 className="w-3 h-3 text-teal-400 inline mr-1" />
                    CAMS statement parsed — Portfolio X-Ray will use this data
                    {parsedCas.confidence < 0.5 && <span className="text-amber-400 ml-2">(low confidence)</span>}
                  </p>
                )}
                {parsedForm16 && (
                  <p className="text-xs text-slate-300">
                    <CheckCircle2 className="w-3 h-3 text-teal-400 inline mr-1" />
                    Form 16 parsed — Tax Wizard profile auto-populated
                    {parsedForm16.confidence < 0.5 && <span className="text-amber-400 ml-2">(low confidence)</span>}
                  </p>
                )}
                {parsedPayslip && (
                  <p className="text-xs text-slate-300">
                    <CheckCircle2 className="w-3 h-3 text-teal-400 inline mr-1" />
                    Payslip parsed — salary data available
                    {parsedPayslip.confidence < 0.5 && <span className="text-amber-400 ml-2">(low confidence)</span>}
                  </p>
                )}
              </div>
              {showExtractedData && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  className="pt-3 border-t border-teal-500/20 space-y-3 text-xs"
                >
                  {parsedCas && (() => {
                    const data = parsedCas.data as { investorName?: string; funds?: { fundName: string; currentValue: number }[] };
                    return (
                      <div>
                        <p className="text-teal-200 font-medium mb-1">CAS — {data.investorName || 'Unknown'}</p>
                        {data.funds && data.funds.slice(0, 3).map((f, i) => (
                          <p key={i} className="text-[10px] text-slate-400 pl-3">{f.fundName}: ₹{new Intl.NumberFormat('en-IN').format(f.currentValue)}</p>
                        ))}
                        {data.funds && data.funds.length > 3 && <p className="text-[10px] text-slate-500 pl-3">+ {data.funds.length - 3} more</p>}
                      </div>
                    );
                  })()}
                  {parsedForm16 && (() => {
                    const data = parsedForm16.data as { grossSalary?: number; taxDeducted?: number; assessmentYear?: string };
                    return (
                      <div>
                        <p className="text-teal-200 font-medium mb-1">Form 16 — AY {data.assessmentYear || '—'}</p>
                        <p className="text-[10px] text-slate-400 pl-3">Gross Salary: ₹{data.grossSalary ? new Intl.NumberFormat('en-IN').format(data.grossSalary) : '—'}</p>
                        <p className="text-[10px] text-slate-400 pl-3">TDS: ₹{data.taxDeducted ? new Intl.NumberFormat('en-IN').format(data.taxDeducted) : '—'}</p>
                      </div>
                    );
                  })()}
                  {parsedPayslip && (() => {
                    const data = parsedPayslip.data as { month?: string; netSalary?: number };
                    return (
                      <div>
                        <p className="text-teal-200 font-medium mb-1">Payslip — {data.month || '—'}</p>
                        <p className="text-[10px] text-slate-400 pl-3">Net Salary: ₹{data.netSalary ? new Intl.NumberFormat('en-IN').format(data.netSalary) : '—'}</p>
                      </div>
                    );
                  })()}
                </motion.div>
              )}
            </div>
          )}

          {/* Dynamic Content Tabs */}
          <AnimatePresence mode="wait">
            {activeTab === 'portfolio' && (
              <motion.div
                key="portfolio"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.2 }}
                className="w-full"
              >
                <ErrorBoundary label="Portfolio X-Ray">
                  <PortfolioXRay profile={profile} />
                </ErrorBoundary>
              </motion.div>
            )}
            {activeTab === 'fire' && (
              <motion.div
                key="fire"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.2 }}
                className="w-full"
              >
                <ErrorBoundary label="FIRE Roadmap">
                  <FIRERoadmap profile={profile} />
                </ErrorBoundary>
              </motion.div>
            )}
            {activeTab === 'tax' && (
              <motion.div
                key="tax"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.2 }}
                className="w-full"
              >
                <ErrorBoundary label="Tax Wizard">
                  <TaxWizard profile={profile} setProfile={setProfile} />
                </ErrorBoundary>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Audit Trail Panel — "How we calculated this" */}
          <div className="mt-10 border border-[#2a2a2a] rounded-2xl overflow-hidden shadow-lg bg-[#141414]">
            <button
              onClick={() => setAuditOpen(!auditOpen)}
              className="w-full flex items-center justify-between p-5 hover:bg-[#1a1a1a] transition-colors"
            >
              <div className="flex items-center gap-3">
                <FileText className="w-5 h-5 text-teal-400" />
                <span className="font-semibold text-white">How we calculated this — Audit Trail</span>
                {auditEntries.length > 0 && (
                  <span className="text-xs text-slate-400 font-mono bg-[#0a0a0a] border border-[#2a2a2a] px-2 py-0.5 rounded-full shadow-inner">
                    {auditEntries.length} agents executed
                  </span>
                )}
              </div>
              {auditOpen ? <ChevronUp className="w-5 h-5 text-teal-500" /> : <ChevronDown className="w-5 h-5 text-teal-500" />}
            </button>
            <AnimatePresence>
              {auditOpen && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="bg-[#0a0a0a] border-t border-[#2a2a2a] p-6"
                >
                  {auditEntries.length > 0 ? (
                    <div className="space-y-3 font-mono text-xs">
                      {auditEntries.map((log, i) => (
                        <div key={i} className="flex items-start gap-4 p-3 rounded-xl bg-[#141414] border border-[#2a2a2a] shadow-sm hover:border-teal-500/30 transition-colors">
                          <span className="text-slate-500 shrink-0 w-16 text-right">{log.latency}</span>
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-1 flex-wrap">
                              <span className="text-white font-semibold">{log.agent}</span>
                              <span className="text-slate-600">•</span>
                              <span className="text-teal-400">{log.model}</span>
                              <span className={cn(
                                "text-[9px] px-2 py-0.5 rounded-full font-medium tracking-wide",
                                log.pipeline === 'Portfolio' ? 'bg-blue-500/20 text-blue-300' :
                                log.pipeline === 'FIRE' ? 'bg-orange-500/20 text-orange-300' :
                                'bg-purple-500/20 text-purple-300'
                              )}>
                                {log.pipeline}
                              </span>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="text-center py-10">
                      <Clock className="w-10 h-10 text-[#333] mx-auto mb-4" />
                      <p className="text-sm text-slate-400 font-medium">No agent executions yet.</p>
                      <p className="text-xs text-slate-500 mt-2 max-w-sm mx-auto">Navigate to a module above to trigger a pipeline — all agent events will appear here in real-time.</p>
                    </div>
                  )}

                  {/* Uploaded Documents summary */}
                  {uploadedDocs.length > 0 && (
                    <div className="mt-8 pt-5 border-t border-[#2a2a2a]">
                      <p className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-4">Uploaded Documents</p>
                      <div className="flex flex-wrap gap-2">
                        {uploadedDocs.map((doc, i) => (
                          <span key={i} className="text-[10px] px-3 py-1.5 rounded-lg bg-[#141414] border border-[#2a2a2a] text-slate-300 font-mono shadow-sm">
                            {doc.file.name} <span className="text-teal-500 mx-1">→</span> {doc.docType}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}
                </motion.div>
              )}
            </AnimatePresence>
          </div>

          {/* Full SEBI Compliance Disclaimer */}
          <div className="mt-8 p-6 rounded-2xl bg-[#141414] border border-[#2a2a2a] shadow-sm">
            <div className="flex items-center gap-2 mb-3">
              <ShieldAlert className="w-5 h-5 text-teal-500" />
              <span className="text-xs font-bold uppercase tracking-widest text-teal-500">Mandatory Compliance Disclaimer</span>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed text-justify">
              {SEBI_DISCLAIMER}
            </p>
          </div>
        </div>
      </main>

      {/* 3. Right Sidebar (Chat Mentor) */}
      <ChatMentor 
        profile={profile}
        uploadedDocs={uploadedDocs}
        setActiveTab={setActiveTab}
        getCrossPipelineData={getCrossPipelineData}
      />
    </div>
  );
}