import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { PieChart, Flame, Calculator, ShieldAlert, FileText, Settings } from 'lucide-react';
import { cn } from '../lib/utils';
import { PortfolioXRay } from './PortfolioXRay';
import { FIRERoadmap } from './FIRERoadmap';
import { TaxWizard } from './TaxWizard';

type Tab = 'portfolio' | 'fire' | 'tax';

export function Dashboard() {
  const [activeTab, setActiveTab] = useState<Tab>('portfolio');

  return (
    <div className="min-h-screen bg-navy-950 flex flex-col md:flex-row">
      {/* Sidebar */}
      <aside className="w-full md:w-64 bg-navy-900 border-r border-navy-800 flex flex-col">
        <div className="p-6">
          <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
            <div className="w-8 h-8 bg-gold-500 rounded-lg flex items-center justify-center">
              <span className="text-navy-950 font-bold text-lg">A</span>
            </div>
            ArthaGPT
          </h1>
        </div>

        <nav className="flex-1 px-4 space-y-2">
          <button
            onClick={() => setActiveTab('portfolio')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'portfolio' ? "bg-navy-800 text-gold-500 shadow-md border border-navy-700" : "text-slate-400 hover:text-slate-200 hover:bg-navy-800/50"
            )}
          >
            <PieChart className="w-5 h-5" />
            <span className="font-medium">Portfolio X-Ray</span>
          </button>
          
          <button
            onClick={() => setActiveTab('fire')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'fire' ? "bg-navy-800 text-gold-500 shadow-md border border-navy-700" : "text-slate-400 hover:text-slate-200 hover:bg-navy-800/50"
            )}
          >
            <Flame className="w-5 h-5" />
            <span className="font-medium">FIRE Roadmap</span>
          </button>

          <button
            onClick={() => setActiveTab('tax')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'tax' ? "bg-navy-800 text-gold-500 shadow-md border border-navy-700" : "text-slate-400 hover:text-slate-200 hover:bg-navy-800/50"
            )}
          >
            <Calculator className="w-5 h-5" />
            <span className="font-medium">Tax Wizard</span>
          </button>
        </nav>

        <div className="p-4 mt-auto">
          <div className="p-4 bg-navy-800 rounded-xl border border-navy-700 space-y-3">
            <div className="flex items-center gap-2 text-slate-300">
              <ShieldAlert className="w-4 h-4 text-gold-500" />
              <span className="text-xs font-medium uppercase tracking-wider">SEBI Disclaimer</span>
            </div>
            <p className="text-[10px] text-slate-500 leading-relaxed">
              This analysis is generated by ArthaGPT, an AI-powered educational tool. Not investment advice. Past performance does not guarantee future returns.
            </p>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 overflow-y-auto p-6 md:p-10">
        <AnimatePresence mode="wait">
          {activeTab === 'portfolio' && (
            <motion.div
              key="portfolio"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
            >
              <PortfolioXRay />
            </motion.div>
          )}
          {activeTab === 'fire' && (
            <motion.div
              key="fire"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
            >
              <FIRERoadmap />
            </motion.div>
          )}
          {activeTab === 'tax' && (
            <motion.div
              key="tax"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
            >
              <TaxWizard />
            </motion.div>
          )}
        </AnimatePresence>
      </main>
    </div>
  );
}
