import { useState, type Dispatch, type SetStateAction } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { PieChart, Flame, Calculator, ShieldAlert, FileText, ChevronDown, ChevronUp, User, Clock } from 'lucide-react';
import { cn } from '../lib/utils';
import { PortfolioXRay } from './PortfolioXRay';
import { FIRERoadmap } from './FIRERoadmap';
import { TaxWizard } from './TaxWizard';
import { ErrorBoundary } from './ErrorBoundary';
import { useAnalysis } from '../contexts/AnalysisContext';
import type { UserProfile, UploadedDocument } from '../App';
import type { AgentEvent } from '../hooks/useSSE';

type Tab = 'portfolio' | 'fire' | 'tax';

const SEBI_DISCLAIMER = `This analysis is generated by ArthaGPT, an AI-powered educational tool. The calculations, projections, and recommendations presented here are for informational and educational purposes only. They do not constitute investment advice, financial planning advice, or any other form of regulated financial service. Past performance of mutual funds does not guarantee future returns. Tax calculations are based on declared inputs and publicly available FY 2025-26 regulations — please verify with a qualified tax professional. Please consult a SEBI-registered investment advisor (RIA) before making any financial decisions. ArthaGPT is not a SEBI-registered entity.`;

export function Dashboard({ profile, setProfile, uploadedDocs = [], onStartOver }: { profile: UserProfile; setProfile: Dispatch<SetStateAction<UserProfile>>; uploadedDocs?: UploadedDocument[]; onStartOver?: () => void }) {
  const [activeTab, setActiveTab] = useState<Tab>('portfolio');
  const [auditOpen, setAuditOpen] = useState(false);
  const { firePipeline, portfolioPipeline, taxPipeline } = useAnalysis();

  // Aggregate real events from all three pipelines for audit trail
  const allEvents: (AgentEvent & { pipeline: string })[] = [
    ...portfolioPipeline.events.map(e => ({ ...e, pipeline: 'Portfolio' })),
    ...firePipeline.events.map(e => ({ ...e, pipeline: 'FIRE' })),
    ...taxPipeline.events.map(e => ({ ...e, pipeline: 'Tax' })),
  ].sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

  const auditEntries = (() => {
    // Group by agent
    const groups = new Map<string, { start?: AgentEvent & { pipeline: string }; complete?: AgentEvent & { pipeline: string } }>();
    for (const e of allEvents) {
      if (e.agent === 'Pipeline') continue;
      const key = `${e.pipeline}::${e.agent}`;
      if (!groups.has(key)) groups.set(key, {});
      const g = groups.get(key)!;
      if (e.type === 'agent_start') g.start = e;
      if (e.type === 'agent_complete') g.complete = e;
    }

    return Array.from(groups.entries()).map(([key, g]) => {
      const [pipeline, agent] = key.split('::');
      const isDeterministic = agent.includes('Engine') || agent.includes('Regime') || agent.includes('Profiler') || agent.includes('Gap');
      const isFlash = agent.includes('Checker') || agent.includes('Injector') || agent.includes('Collector') || agent.includes('Macro');
      const model = isDeterministic ? 'Deterministic Engine' : isFlash ? 'Gemini Flash' : 'Gemini Pro';
      const latency = g.complete?.latencyMs;
      return { pipeline, agent, model, latency: latency !== undefined ? `${latency}ms` : '—' };
    });
  })();

  // Count documents per module
  const portfolioDocs = uploadedDocs.filter(d => d.docType === 'cams' || d.docType === 'demat').length;
  const fireDocs = uploadedDocs.filter(d => d.docType === 'bankstmt' || d.docType === 'insurance').length;
  const taxDocs = uploadedDocs.filter(d => d.docType === 'form16').length;

  return (
    <div className="min-h-screen bg-navy-950 flex flex-col md:flex-row">
      {/* Sidebar */}
      <aside className="w-full md:w-64 bg-navy-900 border-r border-navy-800 flex flex-col">
        <div className="p-6">
          <h1 className="text-2xl font-bold tracking-tight text-white flex items-center gap-2">
            <div className="w-8 h-8 bg-gold-500 rounded-lg flex items-center justify-center">
              <span className="text-navy-950 font-bold text-lg">A</span>
            </div>
            ArthaGPT
          </h1>
        </div>

        <nav className="flex-1 px-4 space-y-2">
          {/* User Profile Summary */}
          {profile.city && (
            <div className="mb-4 p-3 bg-navy-950/50 rounded-xl border border-navy-800">
              <div className="flex items-center gap-2 mb-2">
                <User className="w-4 h-4 text-gold-500" />
                <span className="text-xs font-semibold uppercase tracking-wider text-gold-500">Profile</span>
              </div>
              <p className="text-sm text-white font-medium">{profile.city}, Age {profile.age}</p>
              <p className="text-xs text-slate-400">Income: ₹{(profile.income / 100000).toFixed(0)}L/yr</p>
              {profile.retireAge > 0 && (
                <p className="text-xs text-slate-400">Retire by: {profile.retireAge} • SIP: ₹{profile.monthlySipCurrent ? (profile.monthlySipCurrent / 1000).toFixed(0) + 'K' : '—'}/mo</p>
              )}
            </div>
          )}

          <button
            onClick={() => setActiveTab('portfolio')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'portfolio' ? "bg-navy-800 text-gold-500 shadow-md border border-navy-700" : "text-slate-400 hover:text-slate-200 hover:bg-navy-800/50"
            )}
          >
            <PieChart className="w-5 h-5" />
            <span className="font-medium flex-1 text-left">Portfolio X-Ray</span>
            {portfolioDocs > 0 && <span className="text-[10px] bg-teal-500/20 text-teal-400 px-1.5 py-0.5 rounded-full font-mono">{portfolioDocs} doc{portfolioDocs > 1 ? 's' : ''}</span>}
          </button>
          
          <button
            onClick={() => setActiveTab('fire')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'fire' ? "bg-navy-800 text-gold-500 shadow-md border border-navy-700" : "text-slate-400 hover:text-slate-200 hover:bg-navy-800/50"
            )}
          >
            <Flame className="w-5 h-5" />
            <span className="font-medium flex-1 text-left">FIRE Roadmap</span>
            {fireDocs > 0 && <span className="text-[10px] bg-teal-500/20 text-teal-400 px-1.5 py-0.5 rounded-full font-mono">{fireDocs} doc{fireDocs > 1 ? 's' : ''}</span>}
          </button>

          <button
            onClick={() => setActiveTab('tax')}
            className={cn(
              "w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all duration-200",
              activeTab === 'tax' ? "bg-navy-800 text-gold-500 shadow-md border border-navy-700" : "text-slate-400 hover:text-slate-200 hover:bg-navy-800/50"
            )}
          >
            <Calculator className="w-5 h-5" />
            <span className="font-medium flex-1 text-left">Tax Wizard</span>
            {taxDocs > 0 && <span className="text-[10px] bg-teal-500/20 text-teal-400 px-1.5 py-0.5 rounded-full font-mono">{taxDocs} doc{taxDocs > 1 ? 's' : ''}</span>}
          </button>

          {/* Uploaded Documents Summary in Sidebar */}
          {uploadedDocs.length > 0 && (
            <div className="mt-4 p-3 bg-navy-950/50 rounded-xl border border-navy-800">
              <div className="flex items-center gap-2 mb-2">
                <FileText className="w-4 h-4 text-teal-500" />
                <span className="text-xs font-semibold uppercase tracking-wider text-teal-500">Documents</span>
              </div>
              {uploadedDocs.map((doc, i) => (
                <p key={i} className="text-[10px] text-slate-400 truncate" title={doc.file.name}>
                  {doc.file.name.length > 24 ? doc.file.name.slice(0, 24) + '…' : doc.file.name}
                </p>
              ))}
            </div>
          )}
        </nav>

        <div className="p-4 mt-auto space-y-3">
          {onStartOver && (
            <button
              onClick={onStartOver}
              className="w-full py-2.5 text-sm font-medium text-slate-400 hover:text-white border border-navy-700 hover:border-navy-600 rounded-xl transition-colors"
            >
              ← Start Over
            </button>
          )}
          <div className="p-4 bg-navy-800 rounded-xl border border-navy-700 space-y-3">
            <div className="flex items-center gap-2 text-slate-300">
              <ShieldAlert className="w-4 h-4 text-gold-500" />
              <span className="text-xs font-medium uppercase tracking-wider">Compliance</span>
            </div>
            <p className="text-[10px] text-slate-500 leading-relaxed">
              SEBI-compliant educational tool. Not investment advice. See full disclaimer below each analysis.
            </p>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 overflow-y-auto p-6 md:p-10">
        <AnimatePresence mode="wait">
          {activeTab === 'portfolio' && (
            <motion.div
              key="portfolio"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
            >
              <ErrorBoundary label="Portfolio X-Ray">
                <PortfolioXRay profile={profile} />
              </ErrorBoundary>
            </motion.div>
          )}
          {activeTab === 'fire' && (
            <motion.div
              key="fire"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
            >
              <ErrorBoundary label="FIRE Roadmap">
                <FIRERoadmap profile={profile} />
              </ErrorBoundary>
            </motion.div>
          )}
          {activeTab === 'tax' && (
            <motion.div
              key="tax"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.2 }}
            >
              <ErrorBoundary label="Tax Wizard">
                <TaxWizard profile={profile} setProfile={setProfile} />
              </ErrorBoundary>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Audit Trail Panel — "How we calculated this" */}
        <div className="mt-10 border border-navy-800 rounded-2xl overflow-hidden">
          <button
            onClick={() => setAuditOpen(!auditOpen)}
            className="w-full flex items-center justify-between p-5 bg-navy-900 hover:bg-navy-800/50 transition-colors"
          >
            <div className="flex items-center gap-3">
              <FileText className="w-5 h-5 text-gold-500" />
              <span className="font-semibold text-white">How we calculated this — Audit Trail</span>
              {auditEntries.length > 0 && (
                <span className="text-xs text-slate-500 font-mono bg-navy-800 px-2 py-0.5 rounded">
                  {auditEntries.length} agents executed
                </span>
              )}
            </div>
            {auditOpen ? <ChevronUp className="w-5 h-5 text-slate-400" /> : <ChevronDown className="w-5 h-5 text-slate-400" />}
          </button>
          <AnimatePresence>
            {auditOpen && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                className="bg-navy-950 border-t border-navy-800 p-6"
              >
                {auditEntries.length > 0 ? (
                  <div className="space-y-3 font-mono text-xs">
                    {auditEntries.map((log, i) => (
                      <div key={i} className="flex items-start gap-4 p-3 rounded-lg bg-navy-900/50 border border-navy-800">
                        <span className="text-slate-500 shrink-0 w-16 text-right">{log.latency}</span>
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-1 flex-wrap">
                            <span className="text-gold-500 font-semibold">{log.agent}</span>
                            <span className="text-slate-600">•</span>
                            <span className="text-teal-500">{log.model}</span>
                            <span className={cn(
                              "text-[9px] px-1.5 py-0.5 rounded-full font-medium",
                              log.pipeline === 'Portfolio' ? 'bg-blue-500/10 text-blue-400' :
                              log.pipeline === 'FIRE' ? 'bg-orange-500/10 text-orange-400' :
                              'bg-purple-500/10 text-purple-400'
                            )}>
                              {log.pipeline}
                            </span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <div className="text-center py-8">
                    <Clock className="w-8 h-8 text-slate-600 mx-auto mb-3" />
                    <p className="text-sm text-slate-500">No agent executions yet.</p>
                    <p className="text-xs text-slate-600 mt-1">Navigate to a module above to trigger a pipeline — all agent events will appear here in real-time.</p>
                  </div>
                )}

                {/* Uploaded Documents summary */}
                {uploadedDocs.length > 0 && (
                  <div className="mt-6 pt-4 border-t border-navy-800">
                    <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">Uploaded Documents</p>
                    <div className="flex flex-wrap gap-2">
                      {uploadedDocs.map((doc, i) => (
                        <span key={i} className="text-[10px] px-2 py-1 rounded-full bg-navy-800 border border-navy-700 text-slate-300 font-mono">
                          {doc.file.name} → {doc.docType}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>

        {/* Full SEBI Compliance Disclaimer */}
        <div className="mt-6 p-5 rounded-2xl bg-navy-900/50 border border-navy-800">
          <div className="flex items-center gap-2 mb-3">
            <ShieldAlert className="w-4 h-4 text-gold-500" />
            <span className="text-xs font-bold uppercase tracking-wider text-gold-500">Mandatory Compliance Disclaimer</span>
          </div>
          <p className="text-[11px] text-slate-500 leading-relaxed">
            {SEBI_DISCLAIMER}
          </p>
        </div>
      </main>
    </div>
  );
}
